services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_pg_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    volumes:
      - ./data_pgadmin:/var/lib/pgadmin
  taxi_ingest:
    build:
      context: .  # Assuming Dockerfile is in the same directory
      dockerfile: Dockerfile  # Or specify the path if different
    image: taxi_ingest:v001  # Optional, but good practice
    environment:
      - URL=https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-01.parquet
      - USER=root
      - PASSWORD=root
      - HOST=localhost
      - PORT=5432
      - DB=ny_taxi
      - TB=yellow_taxi_trips
    entrypoint: ["python", "data_loading_parquet.py"]